name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  doc-qa:
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.79
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: README.md
      MD_LINT_CONFIG: .markdownlint.yaml
  python-lint:
    name: Python lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Run flake8
        uses: julianwachholz/flake8-action@v2
        with:
          checkName: "Python Lint"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
