name: Pull Request

on:
  pull_request:
    branches:
      - 'main'

jobs:
  qa:
    uses: stakater/.github/.github/workflows/pull_request_doc_qa.yaml@v0.0.79
    with:
      MD_CONFIG: .github/md_config.json
      DOC_SRC: README.md
      MD_LINT_CONFIG: .markdownlint.yaml
